/**
 * Open API
 * Open API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: liuxiaobin@chainge.finance
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * AppBindAddressParameters.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_AppBindAddressParameters_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_AppBindAddressParameters_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class AppBindAddressParameters : public ModelBase {
public:
  AppBindAddressParameters();
  virtual ~AppBindAddressParameters();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// AppBindAddressParameters members

  /// <summary>
  /// Bind Address
  /// </summary>
  utility::string_t getBindAddress() const;
  bool bindAddressIsSet() const;
  void unsetBindAddress();

  void setBindAddress(const utility::string_t &value);

  /// <summary>
  /// Bind Chain
  /// </summary>
  utility::string_t getBindChain() const;
  bool bindChainIsSet() const;
  void unsetBindChain();

  void setBindChain(const utility::string_t &value);

  /// <summary>
  /// EVM Address
  /// </summary>
  utility::string_t getEvmAddress() const;
  bool evmAddressIsSet() const;
  void unsetEvmAddress();

  void setEvmAddress(const utility::string_t &value);

  /// <summary>
  /// Signature
  /// </summary>
  utility::string_t getSignature() const;
  bool signatureIsSet() const;
  void unsetSignature();

  void setSignature(const utility::string_t &value);

protected:
  utility::string_t m_BindAddress;
  bool m_BindAddressIsSet;
  utility::string_t m_BindChain;
  bool m_BindChainIsSet;
  utility::string_t m_EvmAddress;
  bool m_EvmAddressIsSet;
  utility::string_t m_Signature;
  bool m_SignatureIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_AppBindAddressParameters_H_ */
