/**
 * Open API
 * Open API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: liuxiaobin@chainge.finance
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OpenAPICrossChainInquiryParameters.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPICrossChainInquiryParameters_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPICrossChainInquiryParameters_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class OpenAPICrossChainInquiryParameters : public ModelBase {
public:
  OpenAPICrossChainInquiryParameters();
  virtual ~OpenAPICrossChainInquiryParameters();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// OpenAPICrossChainInquiryParameters members

  /// <summary>
  /// Source Amount
  /// </summary>
  double getAmount() const;
  bool amountIsSet() const;
  void unsetAmount();

  void setAmount(double value);

  /// <summary>
  /// Fee Level
  /// </summary>
  int32_t getFeeLevel() const;
  bool feeLevelIsSet() const;
  void unsetFeeLevel();

  void setFeeLevel(int32_t value);

  /// <summary>
  /// Source Chain
  /// </summary>
  utility::string_t getFromChain() const;
  bool fromChainIsSet() const;
  void unsetFromChain();

  void setFromChain(const utility::string_t &value);

  /// <summary>
  /// Source Chain
  /// </summary>
  utility::string_t getToChain() const;
  bool toChainIsSet() const;
  void unsetToChain();

  void setToChain(const utility::string_t &value);

  /// <summary>
  /// Source Token
  /// </summary>
  utility::string_t getToken() const;
  bool tokenIsSet() const;
  void unsetToken();

  void setToken(const utility::string_t &value);

protected:
  double m_Amount;
  bool m_AmountIsSet;
  int32_t m_FeeLevel;
  bool m_FeeLevelIsSet;
  utility::string_t m_FromChain;
  bool m_FromChainIsSet;
  utility::string_t m_ToChain;
  bool m_ToChainIsSet;
  utility::string_t m_Token;
  bool m_TokenIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPICrossChainInquiryParameters_H_  \
        */
