/**
 * Open API
 * Open API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: liuxiaobin@chainge.finance
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OpenAPIAndAppSubmitOrder.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPIAndAppSubmitOrder_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPIAndAppSubmitOrder_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include "CppRestOpenAPIClient/model/OpenAPIAndAppSubmitAggregateOrder.h"
#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

class OpenAPIAndAppSubmitAggregateOrder;

/// <summary>
///
/// </summary>
class OpenAPIAndAppSubmitOrder : public ModelBase {
public:
  OpenAPIAndAppSubmitOrder();
  virtual ~OpenAPIAndAppSubmitOrder();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// OpenAPIAndAppSubmitOrder members

  /// <summary>
  ///
  /// </summary>
  std::shared_ptr<OpenAPIAndAppSubmitAggregateOrder> getParams() const;
  bool paramsIsSet() const;
  void unsetParams();

  void
  setParams(const std::shared_ptr<OpenAPIAndAppSubmitAggregateOrder> &value);

  /// <summary>
  /// signature
  /// </summary>
  utility::string_t getSignature() const;
  bool signatureIsSet() const;
  void unsetSignature();

  void setSignature(const utility::string_t &value);

protected:
  std::shared_ptr<OpenAPIAndAppSubmitAggregateOrder> m_Params;
  bool m_ParamsIsSet;
  utility::string_t m_Signature;
  bool m_SignatureIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OpenAPIAndAppSubmitOrder_H_ */
