/**
 * Open API
 * Open API
 *
 * The version of the OpenAPI document: 1.0
 * Contact: liuxiaobin@chainge.finance
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 6.5.0.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OpenBindAddressParameter.h
 *
 *
 */

#ifndef ORG_OPENAPITOOLS_CLIENT_MODEL_OpenBindAddressParameter_H_
#define ORG_OPENAPITOOLS_CLIENT_MODEL_OpenBindAddressParameter_H_

#include "CppRestOpenAPIClient/ModelBase.h"

#include <cpprest/details/basic_types.h>

namespace org {
namespace openapitools {
namespace client {
namespace model {

/// <summary>
///
/// </summary>
class OpenBindAddressParameter : public ModelBase {
public:
  OpenBindAddressParameter();
  virtual ~OpenBindAddressParameter();

  /////////////////////////////////////////////
  /// ModelBase overrides

  void validate() override;

  web::json::value toJson() const override;
  bool fromJson(const web::json::value &json) override;

  void toMultipart(std::shared_ptr<MultipartFormData> multipart,
                   const utility::string_t &namePrefix) const override;
  bool fromMultiPart(std::shared_ptr<MultipartFormData> multipart,
                     const utility::string_t &namePrefix) override;

  /////////////////////////////////////////////
  /// OpenBindAddressParameter members

  /// <summary>
  /// Fee Level
  /// </summary>
  int32_t getFeeLevel() const;
  bool feeLevelIsSet() const;
  void unsetFeeLevel();

  void setFeeLevel(int32_t value);

  /// <summary>
  /// Fee To Address
  /// </summary>
  utility::string_t getFeeToAddress() const;
  bool feeToAddressIsSet() const;
  void unsetFeeToAddress();

  void setFeeToAddress(const utility::string_t &value);

protected:
  int32_t m_FeeLevel;
  bool m_FeeLevelIsSet;
  utility::string_t m_FeeToAddress;
  bool m_FeeToAddressIsSet;
};

} // namespace model
} // namespace client
} // namespace openapitools
} // namespace org

#endif /* ORG_OPENAPITOOLS_CLIENT_MODEL_OpenBindAddressParameter_H_ */
